// front-react/src/components/layouts/Footer.tsx
export default function Footer() {
    return <footer className="text-gray-600 dark:text-gray-400 mt-12">
        <div className="container mx-auto px-6 py-6 text-center space-y-1">
            <p dir="ltr">© 2025 roodmap.ir - تمامی حقوق محفوظ است</p>
            <p className="text-sm">ساخته شده با ❤️ توسط <a className="text-purple-500"
                                                           href="https://github.com/NavidEvx">Navid</a></p>
        </div>
    </footer>
}

// front/app/components/layouts/Footer.vue
<template>
    <footer class="text-gray-600 dark:text-gray-400 mt-12">
        <div class="container mx-auto px-6 py-6 text-center space-y-1">
            <p dir="ltr">© 2025 roodmap.ir - تمامی حقوق محفوظ است</p>
            <p class="text-sm">ساخته شده با ❤️ توسط <a class="text-purple-500" href="https://github.com/NavidEvx">Navid</a></p>
        </div>
    </footer>
</template>
